# Generated by Django 4.1.6 on 2023-02-11 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krochet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krochet.address', verbose_name='Order Address')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krochet.crochet', verbose_name='Crochet Requested')),
            ],
        ),
    ]
