# Generated by Django 4.1.6 on 2023-02-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krochet', '0005_address_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
