# Generated by Django 4.1.6 on 2023-03-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krochet', '0007_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='portrait',
            field=models.ImageField(default='/static/images/default/wool.png', upload_to='static/images/portrait/', verbose_name='Portrait'),
        ),
        migrations.AlterField(
            model_name='crochet',
            name='picture',
            field=models.ImageField(default='/static/images/default/wool.png', upload_to='static/images/products/'),
        ),
    ]
