# Generated by Django 4.1.6 on 2023-03-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krochet', '0008_sitesettings_portrait_alter_crochet_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='port',
            field=models.TextField(default='Portfolio', verbose_name='Portfolio'),
        ),
    ]
